CREATE TABLE recipes (
    creator_id INTEGER REFERENCES users(id),
    recipe_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    recipe_name TEXT NOT NULL,
    ingredients TEXT [] NOT NULL,
    directions TEXT [] NOT NULL,
    preptime TEXT NOT NULL,
    cooktime TEXT NOT NULL,
    servingsize TEXT NOT NULL,
    recipe_tags TEXT NOT NULL
)