CREATE TABLE recipes (
    creator_id INTEGER REFERENCES users(id),
    recipe_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    recipe_name TEXT NOT NULL,
    ingredients TEXT [] NOT NULL,
    directions TEXT [] NOT NULL,
    prepTime TEXT NOT NULL,
    cookTime TEXT NOT NULL,
    servingSize TEXT NOT NULL
)